repos:
-   repo: https://github.com/nix-community/nixpkgs-fmt
    rev: v1.2.0
    hooks:
    -   id: nixpkgs-fmt
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.5.7'  
    hooks:
    -   id: autopep8